# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('car_password', models.CharField(max_length=150)),
                ('car_type', models.CharField(default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarEmergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_start_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_start_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_end_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_end_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_current_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_current_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_start_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_start_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_end_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_end_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_current_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_current_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_end_status', models.CharField(default='off', max_length=20)),
                ('edate', models.DateField(auto_now_add=True, null=True)),
                ('estart_time', models.TimeField(auto_now_add=True, null=True)),
                ('eend_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jstart_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('jstart_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('jend_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('jend_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('javg_speed', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('jfuel_con', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('jend_status', models.CharField(default='off', max_length=20)),
                ('jdate', models.DateField(auto_now_add=True, null=True)),
                ('jstart_time', models.TimeField(auto_now_add=True, null=True)),
                ('jend_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_dob', models.DateField()),
                ('driver_uidai', models.IntegerField(unique=True)),
                ('driver_dl', models.IntegerField(unique=True)),
                ('USERNAME_FIELD', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('car_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('car_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('car_speed', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('car_fuel', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('car_temp', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('car_status', models.CharField(default='off', max_length=20)),
                ('car_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='localization.Car')),
                ('car_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='carjourney',
            name='jcar_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Car'),
        ),
        migrations.AddField(
            model_name='carjourney',
            name='jdriver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Driver'),
        ),
        migrations.AddField(
            model_name='caremergency',
            name='ec_car_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='localization.Car'),
        ),
        migrations.AddField(
            model_name='caremergency',
            name='ec_driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='localization.Driver'),
        ),
        migrations.AddField(
            model_name='caremergency',
            name='vc_car_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='localization.Car'),
        ),
        migrations.AddField(
            model_name='caremergency',
            name='vc_driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='localization.Driver'),
        ),
    ]
