# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_remove_driver_driver_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=20, unique=True)),
                ('car_password', models.CharField(max_length=150)),
            ],
        ),
    ]
