# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jstart_lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('jstart_lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('jend_lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('jend_lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('javg_speed', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('jfuel_con', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('jend_status', models.CharField(default='off', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('car_lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('car_speed', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('car_fuel', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('car_temp', models.DecimalField(decimal_places=6, default=0.0, max_digits=6)),
                ('car_status', models.CharField(default='off', max_length=20)),
                ('car_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='carstatus',
            name='car_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Car'),
        ),
        migrations.AddField(
            model_name='carjourney',
            name='jcar_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Car'),
        ),
        migrations.AddField(
            model_name='carjourney',
            name='jdriver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Driver'),
        ),
    ]
