# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0004_auto_20171125_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='carjourney',
            name='jdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
