# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0005_carjourney_jdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.RemoveField(
            model_name='carstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='carstatus',
            name='car_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='localization.Car'),
        ),
    ]
