# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0006_auto_20171125_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstatus',
            name='car_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='localization.Car'),
        ),
    ]
