# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0007_auto_20171125_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='carjourney',
            name='jend_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carjourney',
            name='jstart_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carjourney',
            name='jdate',
            field=models.DateField(auto_now=True),
        ),
    ]
