# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0008_auto_20171126_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carjourney',
            name='jend_time',
            field=models.TimeField(default=models.TimeField(auto_now=True)),
        ),
    ]
