# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0009_auto_20171126_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carjourney',
            name='javg_speed',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='carjourney',
            name='jend_lat',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='carjourney',
            name='jend_lon',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='carjourney',
            name='jfuel_con',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='carjourney',
            name='jstart_lat',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='carjourney',
            name='jstart_lon',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15),
        ),
    ]
