# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0011_auto_20171130_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carjourney',
            name='jdate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='carjourney',
            name='jstart_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
