# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0013_auto_20171130_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEmergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_start_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_start_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_end_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_end_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_current_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_current_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_start_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_start_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_end_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_end_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_current_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('ec_current_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('vc_end_status', models.CharField(default='off', max_length=20)),
                ('edate', models.DateField(auto_now_add=True, null=True)),
                ('estart_time', models.TimeField(auto_now_add=True, null=True)),
                ('eend_time', models.TimeField(auto_now=True)),
                ('ec_car_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='localization.Car')),
                ('ec_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='localization.Driver')),
                ('vc_car_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='localization.Car')),
                ('vc_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='localization.Driver')),
            ],
        ),
    ]
